[env:waveshare-s3-epaper]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; upload_port und monitor_port automatisch ermitteln (macOS: /dev/cu.usbmodem*)

board_build.partitions = huge_app.csv
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    zinggjm/GxEPD2@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit BusIO@^1.16.2
